### ISSUE TITLE
MEGA 2560 

### ISSUE THREAD

**Issue by Raphitech** [ripred/CPUTemp#2]
Tried your Library on an Arduino MEGA 2560 but the results i got are wrong it mesures about 500°C which is obviously wrong (tried with example code) but the same code worked flawless on an Arduino UNO 
Any Help appreciated

**Comment by ripred** [comment]
The technique used relies on the capabilities built into the silicon of the specific processor and uses specifically named registers. The technique relies on a Microchip Application Note that unfortunately I cannot recall the specific AN number for at the moment. That AN should be the source of truth for which specific processors the technique will and will not work for and the processors supported are inherently unchangeable since it is baked into the silicon. It is quite possible (and likely given your description of your experience trying it with that processor) that the ATMega2650 is not listed among the supported processors.

**Comment by ripred** [comment]
Based on your feedback I also updated the README to specify the ATMega328 processor. If I can find the Microchip application note I used I will update things if I find that other processors are capable. Thanks for the feedback.
